load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cmd",
    srcs = ["cmd.go"],
    importpath = "github.com/adnoctem/gopskit/internal/fillr/cmd",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/fillr/app",
        "//pkg/fsi",
        "//pkg/helpers",
        "@com_github_spf13_cobra//:cobra",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)

alias(
    name = "go_default_library",
    actual = ":cmd",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "cmd_test",
    srcs = ["cmd_test.go"],
    embed = [":cmd"],
    deps = [
        "//internal/fillr/app",
        "//pkg/core",
        "@com_github_stretchr_testify//assert",
    ],
)
