load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "config",
    srcs = [
        "config.go",
        "hooks.go",
    ],
    importpath = "github.com/adnoctem/gopskit/internal/carto/config",
    visibility = ["//:__subpackages__"],
    deps = [
        "//pkg/fsi",
        "//pkg/kube",
        "//pkg/log",
        "//pkg/proc",
        "@in_gopkg_yaml_v3//:yaml_v3",
        "@io_k8s_api//core/v1:core",
    ],
)

alias(
    name = "go_default_library",
    actual = ":config",
    visibility = ["//:__subpackages__"],
)
