load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "helm",
    srcs = [
        "apply.go",
        "chart.go",
        "client.go",
        "diff.go",
        "history.go",
        "rollback.go",
        "values.go",
    ],
    importpath = "github.com/adnoctem/gopskit/pkg/helm",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/fsi",
        "@cat_dario_mergo//:mergo",
        "@com_github_google_go_cmp//cmp",
        "@in_gopkg_yaml_v3//:yaml_v3",
        "@io_k8s_cli_runtime//pkg/genericclioptions",
        "@io_k8s_utils//diff",
        "@sh_helm_helm_v3//pkg/action",
        "@sh_helm_helm_v3//pkg/chart",
        "@sh_helm_helm_v3//pkg/chart/loader",
        "@sh_helm_helm_v3//pkg/cli",
        "@sh_helm_helm_v3//pkg/registry",
        "@sh_helm_helm_v3//pkg/release",
        "@sh_helm_helm_v3//pkg/storage/driver",
    ],
)

alias(
    name = "go_default_library",
    actual = ":helm",
    visibility = ["//visibility:public"],
)

go_test(
    name = "helm_test",
    srcs = [
        "apply_test.go",
        "chart_test.go",
        "diff_test.go",
        "helm_test.go",
        "history_test.go",
        "rollback_test.go",
        "values_test.go",
    ],
    data = glob(["testdata/**"]),
    embed = [":helm"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@sh_helm_helm_v3//pkg/action",
        "@sh_helm_helm_v3//pkg/chartutil",
        "@sh_helm_helm_v3//pkg/kube/fake",
        "@sh_helm_helm_v3//pkg/storage",
        "@sh_helm_helm_v3//pkg/storage/driver",
    ],
)
