load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "helm",
    srcs = [
        "apply.go",
        "chart.go",
        "client.go",
        "diff.go",
        "history.go",
        "rollback.go",
        "values.go",
    ],
    importpath = "github.com/fmjstudios/gopskit/pkg/helm",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/fsi",
        "@com_github_google_go_cmp//cmp",
        "@com_github_imdario_mergo//:mergo",
        "@in_gopkg_yaml_v3//:yaml_v3",
        "@io_k8s_cli_runtime//pkg/genericclioptions",
        "@io_k8s_utils//diff",
        "@sh_helm_helm_v3//pkg/action",
        "@sh_helm_helm_v3//pkg/chart",
        "@sh_helm_helm_v3//pkg/chart/loader",
        "@sh_helm_helm_v3//pkg/cli",
        "@sh_helm_helm_v3//pkg/registry",
        "@sh_helm_helm_v3//pkg/release",
    ],
)

alias(
    name = "go_default_library",
    actual = ":helm",
    visibility = ["//visibility:public"],
)
