load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "waltr_lib",
    srcs = ["main.go"],
    importpath = "github.com/adnoctem/gopskit/cmd/waltr",
    visibility = ["//visibility:private"],
    x_defs = {
        "github.com/adnoctem/gopskit/pkg/stamp.Version": module_version(),
        "github.com/adnoctem/gopskit/pkg/stamp.BuildDate": "{BUILD_DATE}",
        "github.com/adnoctem/gopskit/pkg/stamp.CommitSHA": "{GIT_COMMIT_SHA}",
        "github.com/adnoctem/gopskit/pkg/stamp.Branch": "{GIT_BRANCH}",
        "github.com/adnoctem/gopskit/pkg/stamp.Platform": "{PLATFORM}",
        "github.com/adnoctem/gopskit/pkg/stamp.GoVersion": "{GO_VERSION}",
    },
    deps = [
        "//internal/waltr/app",
        "//internal/waltr/cmd",
        "//pkg/stamp",
    ],
)

go_binary(
    name = "waltr",
    out = "waltr",
    embed = [":waltr_lib"],
    visibility = ["//visibility:public"],
)
