load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "env",
    srcs = ["env.go"],
    importpath = "github.com/adnoctem/gopskit/pkg/env",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":core",
    visibility = ["//visibility:public"],
)

go_library(
    name = "core",
    srcs = [
        "api.go",
        "env.go",
    ],
    importpath = "github.com/adnoctem/gopskit/pkg/core",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/fsi",
        "//pkg/kube",
        "//pkg/log",
        "//pkg/proc",
        "//pkg/stamp",
    ],
)

go_test(
    name = "core_test",
    srcs = ["env_test.go"],
    embed = [":core"],
    deps = ["@com_github_stretchr_testify//assert"],
)
