load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "vault",
    srcs = [
        "auth.go",
        "secrets.go",
        "system.go",
        "vault.go",
    ],
    importpath = "github.com/adnoctem/gopskit/pkg/api/vault",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/api",
        "//pkg/fsi",
        "//pkg/log",
        "@com_github_hashicorp_vault_client_go//:vault-client-go",
        "@com_github_hashicorp_vault_client_go//schema",
    ],
)

alias(
    name = "go_default_library",
    actual = ":vault",
    visibility = ["//visibility:public"],
)

go_test(
    name = "vault_test",
    srcs = ["vault_test.go"],
    embed = [":vault"],
    deps = [
        "//pkg/api",
        "@com_github_hashicorp_vault_client_go//:vault-client-go",
        "@com_github_stretchr_testify//assert",
    ],
)
