load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "keycloak",
    srcs = [
        "check.go",
        "create.go",
        "errors.go",
        "get.go",
        "keycloak.go",
        "util.go",
    ],
    importpath = "github.com/adnoctem/gopskit/pkg/api/keycloak",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/api",
        "//pkg/fsi",
        "//pkg/helpers",
        "//pkg/log",
        "@com_github_nerzal_gocloak_v14//:gocloak",
        "@org_golang_x_text//cases",
        "@org_golang_x_text//language",
    ],
)

alias(
    name = "go_default_library",
    actual = ":keycloak",
    visibility = ["//visibility:public"],
)

go_test(
    name = "keycloak_test",
    srcs = ["keycloak_test.go"],
    embed = [":keycloak"],
    deps = [
        "@com_github_nerzal_gocloak_v14//:gocloak",
        "@com_github_stretchr_testify//assert",
    ],
)
