name: 'Run Super-Linter'

on: ['push', 'pull_request']

permissions: {}

jobs:
  lint:
    name: Super-Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Superlinter
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (.*.mod|.*.sum)
          BASH_EXEC_IGNORE_LIBRARIES: true
          # mostly false positives
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_JSCPD: false
          VALIDATE_KUBERNETES_KUBECONFORM: false
          # there individual Go files to be linted (all modules)
          VALIDATE_GO: false
          # disable for now, as it's a bit too early for strict rules
          VALIDATE_GO_MODULES: false
